spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: none
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
    show-sql: false
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: core-service-dev
    password: core-service-dev

grpc:
  client:
    core:
      host: localhost
      port: 9098
    way4:
      host: localhost
      port: 9098
    ecrm:
      host: localhost
      port: 9097
